# Generated by Django 5.0.4 on 2024-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField()),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('list_of_post_ids', models.TextField(default='[]')),
                ('list_of_follower_usernames', models.TextField(default='[]')),
                ('list_of_following_usernames', models.TextField(default='[]')),
                ('list_of_blocked_user_usernames', models.TextField(default='[]')),
                ('list_of_collection_ids', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField()),
                ('last_login', models.DateField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_administrator', models.BooleanField(default=False)),
            ],
        ),
    ]
