# Generated by Django 5.0.4 on 2024-04-27 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.TextField()),
                ('label_type', models.TextField()),
                ('material', models.TextField()),
                ('genre', models.TextField()),
                ('is_own_artwork', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=50)),
                ('content', models.TextField(blank=True, max_length=200)),
                ('list_of_usernames', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('list_of_post_ids', models.TextField(default='[]')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=50)),
                ('is_wikidata_api', models.BooleanField(default=False)),
                ('textual_content', models.TextField(blank=True, max_length=600)),
                ('number_of_likes', models.IntegerField()),
                ('list_of_label_ids', models.TextField(default='[]')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifactapp.image')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifactapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifactapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('list_of_post_ids', models.TextField(default='[]')),
                ('list_of_follower_usernames', models.TextField(default='[]')),
                ('list_of_following_usernames', models.TextField(default='[]')),
                ('list_of_blocked_user_usernames', models.TextField(default='[]')),
                ('profile_picture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artifactapp.image')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
