# Generated by Django 5.0.4 on 2024-04-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifactapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
    ]
