# Generated by Django 5.0.4 on 2024-04-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifactapp', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
