# Generated by Django 5.0.4 on 2024-04-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifactapp', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
