# Generated by Django 5.0.4 on 2024-04-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifactapp', '0006_alter_profile_username_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
