export const indexPath = '/'
export const loginPath = '/login'
export const registerPath = '/register'
export const profilePath = '/profile'
export const programPath = '/program'
export const progressPath = '/progress'
export const trainingPath = '/training'